### ISSUE TITLE
Setup LogicApp testing infrastructure for integration tests

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/testing-framework#19]
**Is your feature request related to a problem? Please describe.**
Currently, the integration tests require some extra configuration values before the tests can be run.
The tests require credentials to manage the logic app resources in Azure.

Also, the variables should be at as a [variable group](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml).

**Describe the solution you'd like**
Currently, the tests require following values:
* `#{LogicApps.SubscriptionId}#`
* `#{LogicApps.TenantId}#`
* `#{LogicApps.ClientId}#`
* `#{LogicApps.ClientSecret}#`
* `#{LogicApps.ResourceGroup}#`

**Describe alternatives you've considered**
Maybe there's already such a testing infrastructure set up, but need the values just be available for thie repo.

**Additional context**
https://github.com/invictus-integration/testing-framework/blob/master/src/Invictus.TestLibrary.LogicApps.UnitTests/app.config

**Comment by stijnmoreels** [comment]
@mbraekman , the 'invictus-tst-testing' resource group is not something that is available for me. Should I contact Toon about this? 
+ all the ID's in the the variable group are made secrets, so there's no way for me to know what resources, applications, ... it was refered too. We can't move variable groups across projects and can't give access to them from across projects (AFAIK).

Any thoughts?

**Comment by tomkerkhove** [comment]
Maybe this is something @mbraekman can pick up to fill them in in a variable you've created @stijnmoreels ?

**Comment by mbraekman** [comment]
Just checked, but I seem to be lacking the access rights to grant you access to the resource group, so I'll check with Toon for that.

Regarding the secrets/ID's, I propose to create a LastPass folder to add this type of information - which I'll do within the next minute and share it with the both of you.
Not that I don't want to add them directly into the created variables, just seems to be a more future-proof approach.

**Comment by tomkerkhove** [comment]
Thanks - We already have a folder so will invite you @mbraekman

**Comment by stijnmoreels** [comment]
> Thanks - We already have a folder so will invite you @mbraekman

We already have a folder for invictus?

**Comment by tomkerkhove** [comment]
No, we'll re-use Arcus one

**Comment by stijnmoreels** [comment]
All values are now in the variable group. Which variables should be in the variable template?

**Comment by tomkerkhove** [comment]
I'd go with resource group & client id
