### ISSUE TITLE
Authorize user to MyGet & NuGet package endpoint

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/testing-framework#21]
**Is your feature request related to a problem? Please describe.**
To publish packages, we have to authorize an user to the MyGet and NuGet sources.

**Describe the solution you'd like**
* Use the `arcus-automation` user and create a [Service Connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml) to MyGet and NuGet.
* Create a new user and create a [Service Connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml) to MyGet and NuGet.

**Comment by tomkerkhove** [comment]
Created!
