### ISSUE TITLE
Migrate to .NET Core 3.1

### ISSUE THREAD

**Issue by tomkerkhove** [invictus-integration/testing-framework#22]
Migrate to .NET Core 3.1 instead of .NET Framework

**Comment by mbraekman** [comment]
Be aware that the Azure Logic App SDK currently has a dependency on .Net Framework 4.5.2: https://www.nuget.org/packages/Microsoft.Azure.Management.Logic/

**Comment by tomkerkhove** [comment]
It's an old one which is no longer maintained so we'll have to use the new SDK - Either https://github.com/Azure/azure-sdk-for-net or https://github.com/Azure/azure-libraries-for-net
