### ISSUE TITLE
Provide support for all Azure Clouds

### ISSUE THREAD

**Issue by tomkerkhove** [invictus-integration/testing-framework#30]
**Is your feature request related to a problem? Please describe.**
Provide support for all Azure Clouds so that our library can connect to other clouds such as government, china, stack, etc.

**Describe the solution you'd like**
Provide an overload of `LogicAuthentication.UsingServicePrincipal` which takes in the desired cloud

**Comment by tomkerkhove** [comment]
This will have impact on how we authenticate since it will use different URLs

**Comment by stijnmoreels** [comment]
Just to be clear, this is the `https://login.windows.net/` URL, not the `https://management.azure.com/` URL that has to be configurable?

**Comment by tomkerkhove** [comment]
We should allow them to configure the enum and use the corresponding URL. This is part of the SDK, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.azureenvironment?view=azure-dotnet which gives you the required URLs.

I don't think there is an enum for it, but created my own for Promitor: https://github.com/tomkerkhove/promitor/blob/2af545c19ab24d9d63416c960e4aef6cd4913224/src/Promitor.Core/Serialization/Enum/AzureCloud.cs
