### ISSUE TITLE
Provide Logic App + ARM used to test "TemporaryUpdateAsync" and "RunAsync"

### ISSUE THREAD

**Issue by mbraekman** [invictus-integration/testing-framework#31]
**Is your feature request related to a problem? Please describe.**
Provide a Logic App which can be used to validate the functionality of the `TemporaryUpdateAsync`-method.

**Describe the solution you'd like**
These steps are to be taken:
- [x] create basic logic app for this purpose
- [x] provide sample ARM to perform the update of the logic app.

**Comment by stijnmoreels** [comment]
Relates to:  https://github.com/invictus-integration/testing-framework/pull/27#discussion_r439293840

**Comment by stijnmoreels** [comment]
Relates to https://github.com/invictus-integration/testing-framework/pull/27#discussion_r439228815

**Comment by mbraekman** [comment]
A new Logic App has been created, which can be used for the 2 test-cases as mentioned in the subject.
This Logic App still allows you to provide a "CorrelationId"-header, but does not require you to.

The new Logic App can be found here:
- resource group: invictus-tst-testing
- name: invictus-tst-testing-rcv-trigger-http

As it sits now, it is about to return a simple response:
{
    "response": "Original"
}

After using the provided ARM-template, it should return this:
{
    "response": "Updated"
}

**Comment by mbraekman** [comment]
@stijnmoreels,

I've added the ARM-template underneath the folder "LogicAppDefinitions" within the Integration-testing project (see my commit in a separate branch).

Filename: rcv-trigger-http.json
