### ISSUE TITLE
Question - Should we integrate `ISecretProvider` in here?

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/testing-framework#34]
Question - Should we integrate `ISecretProvider` in here?

_Originally posted by @tomkerkhove in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDI2MzIxNzIz/pull_request_reviews/more_threads_

**Comment by stijnmoreels** [comment]
We should first redesign the authentication models in the security repo, right? Since we now depend on a keyvault client to return while we need a logicapps management client.

**Comment by tomkerkhove** [comment]
I think all you need is to lookup the secret here: https://github.com/invictus-integration/testing-framework/blob/ce47b2362141260ed3b31a5658abb18a9527bc67/src/Invictus.Testing.LogicApps/LogicAuthentication.cs#L58

All the rest is ok to be used how it is now

**Comment by stijnmoreels** [comment]
> I think all you need is to lookup the secret here:
> 
> https://github.com/invictus-integration/testing-framework/blob/ce47b2362141260ed3b31a5658abb18a9527bc67/src/Invictus.Testing.LogicApps/LogicAuthentication.cs#L58
> 
> All the rest is ok to be used how it is now

Ok, we could do that. And pass allong the secret provider and the client secret key for this. But also, this library is gonna be used in test projects and I don't think there's always need for this to do? (We also don't use secret providers if we get a client secret in our tests for example.)

**Comment by tomkerkhove** [comment]
That's true, I wouldn't make it mandatory but more open in case people want to use it.
