### ISSUE TITLE
Allow authentication using just a token

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [invictus-integration/testing-framework#52]
**Is your feature request related to a problem? Please describe.**
In the current implementation the authentication option(s) are limited to authentication using the service principal secret. 

**Describe the solution you'd like**
A authentication method that allows usage of a token. 

**Describe alternatives you've considered**
None :)

**Additional context**
This secret is to my opinion quite sensitive data and I prefer to store it nowhere except the Azure DevOps service connection where it can be leveraged via pipelines. Normally it's possible to retrieve a token using a Azure CLI or Azure powershell in a pipeline step and feed that token to the next step (being the step where the tests get executed).

I'm not 100% sure yet on what the best option would be to feed the token to the tests from the pipeline and leverage it in the code. Let's brainstorm on that one!

**Comment by tomkerkhove** [comment]
From what I'm seeing you could fork it and try passing that token here: https://github.com/invictus-integration/testing-framework/blob/master/src/Invictus.Testing.LogicApps/LogicAppAuthentication.cs#L89

If that works out for you, we can provide you wit the required controls to use that authentication.
