### ISSUE TITLE
Provide documentation on how to authenticate

### ISSUE THREAD

**Issue by tomkerkhove** [invictus-integration/testing-framework#53]
**Is your feature request related to a problem? Please describe.**
Provide documentation on how to authenticate:
- How do we authenticate in the library
- What permissions are required

**Additional context**
It might already be there but that I've missed it.

**Comment by stijnmoreels** [comment]
There's no dedicated page for that, no. We provide in both the Logic Apps client and provider docs a preceding section on how to setup the authentication.
But there's no comment on what these permissions are. What should they be actually?

**Comment by tomkerkhove** [comment]
Can you share a link to those sections please? Might be good to provide a dedicated navigation entry for that to better surface the supported options.

I'd ask you or @mbraekman what is required to be honest; might be good to check the underlying SDK if they have documented it.

**Comment by stijnmoreels** [comment]
> Can you share a link to those sections please?

[here](https://invictus-integration.github.io/testing-framework/#/logic-apps/control-single-logicapp?id=features) and [here](https://invictus-integration.github.io/testing-framework/#/logic-apps/polling-logicapp-runs?id=features).

**Comment by tomkerkhove** [comment]
Ok, looks pretty much as duplication to me.

I would move the supported authentication parts to here:
![image](https://user-images.githubusercontent.com/4345663/88632553-06808c80-d0b4-11ea-92f3-3c55ea8cfaef.png)

And then the respective pages can use this:
```csharp
using (var logicApp = await LogicAppClient.CreateAsync(resourceGroup, logicAppName, authentication))
{
}
```

```csharp
var provider = LogicAppsProvider.LocatedAt(resourceGroupName, logicAppName, authentication);
```

**Comment by mbraekman** [comment]
> What should they be actually?

Typically we tend to re-use the existing service principal, which has been created to connect Azure DevOps to the Azure Subscription, as this already has the required permissions (_Contributor_) and doesn't require the setup of an additional SP.

However, moving forward it would be better - from a security-perspective - to have a separate SP created which is "_Logic App Contributor_" and "_Reader_" on subscription-level. (Not entirely sure about the _Reader_-role)
This should suffice, as this grants sufficient access to the Logic Apps, which it is going to manage/control, while no other resource types are touched.

**Comment by tomkerkhove** [comment]
Let's go with [Logic App Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#logic-app-contributor)  since [Logic App Operator](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#logic-app-operator) won't cut it since we change the Logic App as well, right?

We should not advise to use Contributor indeed!

**Comment by mbraekman** [comment]
Correct, _Logic App Operator_ won't work when attempting to add static results or when updating the LA.

**Comment by mbraekman** [comment]
Just noticed a small mistake in the current documentation, which can be resolved as part of this issue:
On [the page](https://invictus-integration.github.io/testing-framework/#/logic-apps/polling-logicapp-runs) explaining how to poll for Logic App runs, underneath the Features header, there is a reference to `LogicAppClient`, instead of `LogicAppsProvider`.

>All the following features uses the _LogicAppClient_ which can be created using:

should be:

>All the following features uses the _LogicAppsProvider_ which can be created using:

**Comment by tomkerkhove** [comment]
> Just noticed a small mistake in the current documentation, which can be resolved as part of this issue:
> On [the page](https://invictus-integration.github.io/testing-framework/#/logic-apps/polling-logicapp-runs) explaining how to poll for Logic App runs, underneath the Features header, there is a reference to `LogicAppClient`, instead of `LogicAppsProvider`.
> 
> > All the following features uses the _LogicAppClient_ which can be created using:
> 
> should be:
> 
> > All the following features uses the _LogicAppsProvider_ which can be created using:

@stijnmoreels Looks like the issue was closed but don't think this is resolved, or is it?

**Comment by stijnmoreels** [comment]
We changed the authentication and took this issue into account, yes. Normally it's all good.
